version: "3.3"

services:
  lavalink:
    image: "fredboat/lavalink:v3-update-lp-alpine"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - "2333:2333"
    restart: always
  discord-bot:
    build: .
    container_name: Ganghoven
    depends_on:
      - lavalink
    environment:
      - DOTENV_PATH=.env.prod
    restart: always
